basePath: /api
host: '{{.Host}}'
info:
  contact:
    name: Yoko
  description: CatDogs API 文档
  license: {}
  title: CatDogs API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 邮箱账号
        in: formData
        name: email
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "data": {}, "msg": "success"}'
          schema:
            type: string
      summary: 登录接口
      tags:
      - 用户
swagger: "2.0"
