basePath: /api
definitions:
  libs.R:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
  post.SetPost:
    properties:
      author:
        type: string
      content:
        type: string
      title:
        type: string
    required:
    - author
    - content
    - title
    type: object
  user.User:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: '{{.Host}}'
info:
  contact:
    name: Yoko
  description: CatDogs API 文档
  license: {}
  title: CatDogs API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: Login Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/user.User'
          type: object
      produces:
      - application/json
      responses:
        "0":
          schema:
            $ref: '#/definitions/libs.R'
            type: object
        "999":
          description: 服务器出问题
          schema:
            type: string
        "1002":
          description: 用户不存在
          schema:
            type: string
        "1003":
          description: 密码错误
          schema:
            type: string
      summary: 登录接口
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 注册接口
      parameters:
      - description: Register Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/user.User'
          type: object
      produces:
      - application/json
      responses:
        "0":
          schema:
            $ref: '#/definitions/libs.R'
            type: object
        "999":
          description: 服务器出问题
          schema:
            type: string
        "1000":
          description: 用户已存在
          schema:
            type: string
      summary: 注册接口
      tags:
      - 用户
  /setpost:
    post:
      consumes:
      - application/json
      description: 发布文章
      parameters:
      - description: SetPost Params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/post.SetPost'
          type: object
      produces:
      - application/json
      responses:
        "0":
          schema:
            $ref: '#/definitions/libs.R'
            type: object
        "999":
          description: 服务器出问题
          schema:
            type: string
        "3000":
          description: 参数错误
          schema:
            type: string
      summary: 发布文章
      tags:
      - 文章
swagger: "2.0"
