basePath: /api
host: '{{.Host}}'
info:
  contact:
    name: Yoko
  description: CatDogs API 文档
  license: {}
  title: CatDogs API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 邮箱账号
        in: formData
        name: email
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: '{"code": 0, "data": {}, "msg": "success"}'
          schema:
            type: string
        "999":
          description: 服务器出问题
          schema:
            type: string
        "1002":
          description: 用户不存在
          schema:
            type: string
        "1003":
          description: 密码错误
          schema:
            type: string
      summary: 登录接口
      tags:
      - 用户
  /register:
    post:
      consumes:
      - application/json
      description: 注册接口
      parameters:
      - description: 邮箱账号
        in: formData
        name: email
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: '{"code": 0, "data": {}, "msg": "success"}'
          schema:
            type: string
        "999":
          description: 服务器出问题
          schema:
            type: string
        "1000":
          description: 用户已存在
          schema:
            type: string
      summary: 注册接口
      tags:
      - 用户
  /setpost:
    post:
      consumes:
      - application/json
      description: 发布文章
      parameters:
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 作者
        in: formData
        name: author
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: '{"code": 0, "data": {}, "msg": "success"}'
          schema:
            type: string
        "999":
          description: 服务器出问题
          schema:
            type: string
        "3000":
          description: 参数错误
          schema:
            type: string
      summary: 发布文章
      tags:
      - 文章
swagger: "2.0"
